// Файл с данными инпутов, которые предстоить рендерить

const inputData = [
  {
    name: "email",
    type: "email",
    labelText: "E-mail",
    id: "email-input",
    isRequired: true,
    placeholder: "avc@gmail.com",
    icon: false,
    alt: false,
    isFullLength: false,
  },
  {
    name: "phone",
    type: "tel",
    labelText: "Телефон",
    id: "phone-input",
    isRequired: true,
    placeholder: "+7 933 848-34-33",
    icon: false,
    alt: false,
    isFullLength: false,
  },
  {
    name: "organization-name",
    type: "text",
    labelText: "Название организации",
    id: "org-name-input",
    isRequired: true,
    placeholder: "АВЦ",
    icon: false,
    alt: false,
    isFullLength: false,
  },
  {
    name: "personal-website",
    type: "text",
    labelText: "",
    id: "personal-website-input",
    isRequired: false,
    placeholder: "avc.ru",
    icon: "./img/Icon_personal_website.svg",
    alt: "Иконка Личного сайта",
    isFullLength: true,
  },
  {
    name: "vk",
    type: "text",
    labelText: "",
    id: "vk-input",
    isRequired: false,
    placeholder: "vk.com/shans",
    icon: "./img/Icon_vk.svg",
    alt: "Иконка Сайта Вконтакте",
    isFullLength: true,
  },
  {
    name: "ok",
    type: "text",
    labelText: "",
    id: "ok-input",
    isRequired: false,
    placeholder: "ok.com/shans",
    icon: "./img/Icon_ok.svg",
    alt: "Иконка Сайта Одноклассники",
    isFullLength: true,
  },
  {
    name: "facebook",
    type: "text",
    labelText: "",
    id: "facebook-input",
    isRequired: false,
    placeholder: "facebook.com/shans",
    icon: "./img/Icon_facebook.svg",
    alt: "Иконка Сайта Фейсбук",
    isFullLength: true,
  },
  {
    name: "instagram",
    type: "text",
    labelText: "",
    id: "instagram-input",
    isRequired: false,
    placeholder: "instagram.com/shans",
    icon: "./img/Icon_instagram.svg",
    alt: "Иконка Сайта Инстаграмм",
    isFullLength: true,
  },
  {
    name: "youtube",
    type: "text",
    labelText: "",
    id: "youtube-input",
    isRequired: false,
    placeholder: "youtube.com/shans",
    icon: "./img/Icon_youtube.svg",
    alt: "Иконка Сайта Ютуб",
    isFullLength: true,
  },
  {
    name: "manager",
    type: "text",
    labelText: "Руководитель",
    id: "youtube-input",
    isRequired: false,
    placeholder: "Александров Иван Васильевич",
    icon: false,
    alt: false,
    isFullLength: true,
  },
];

export default inputData;
